COMMENT ON TABLE public.algapiocoracidhistacid IS 'ALGORITMO - Junção de todas as atividades potencialmente impactantes (Fontes Fixas e Móveis), Áreas Contaminadas e Históricos de Ocorrência de Acidentes, para gerar áreas de risco ambiental';
COMMENT ON TABLE public.algdissolveareariscoamb IS 'ALGORITMO - Cruzamento das atividades potencialmente impactantes com os sítios frágeis para a identificação das áreas de risco ambiental';
COMMENT ON TABLE public.algsitiofragil IS 'ALGORITMO - Junção de todos os sítios frágeis e vulneráveis';
COMMENT ON TABLE public.areacontampassivoambiental IS 'Área Contaminada - Passivo Ambiental';
COMMENT ON TABLE public.arealegalmenteprotegida IS 'Área Legalmente Protegida';
COMMENT ON TABLE public.arearecargaaquifero IS 'Áreas de Recarga de Aquífero';
COMMENT ON TABLE public.areariscoambiental IS 'ALGORITMO - Agrega polígonos adjacentes com os mesmos graus de risco para gerar as áreas de risco ambiental';
COMMENT ON TABLE public.assentamentohumano IS 'Assentamento Humano';
COMMENT ON TABLE public.captacao IS 'Pontos de Captação de Água';
COMMENT ON TABLE public.caractativpotimpactanteempresa IS 'Caracterização da Atividade Potencialmente Impactante - Empresa';
COMMENT ON TABLE public.caractativpotimpactanteemptransp IS 'Caracterização da Atividade Potencialmente Impactante - Empresa Transporte';
COMMENT ON TABLE public.caractprodresquimenvolvido IS 'Caracterização do Produto ou Resíduo Químico Envolvido';
COMMENT ON TABLE public.caractprodutoquimico IS 'Caracterização Produtos Químicos';
COMMENT ON TABLE public.caractprodutoquimtransportado IS 'Caracterização Produtos Químicos Transportados';
COMMENT ON TABLE public.contaminacaoambiental IS 'Registro de Ocorrência de Contaminação Ambiental (solo, ar e água)';
COMMENT ON TABLE public.empresa IS 'Relação de Empresas Cadastradas';
COMMENT ON TABLE public.empresatransporte IS 'Relação de Empresas de Transporte Cadastradas';
COMMENT ON TABLE public.estrutcontinstrgestambareacontam IS 'Estruturas de Contenção e Instrumentos de Gestão Ambiental - Área Contaminada';
COMMENT ON TABLE public.estrutcontinstrgestambempresa IS 'Estruturas de Contenção e Instrumentos de Gestão Ambiental - Empresa';
COMMENT ON TABLE public.estrutcontinstrgestambemptransp IS 'Estruturas de Contenção e Instrumentos de Gestão Ambiental - Empresa Transporte';
COMMENT ON TABLE public.fichaprodutoquimico IS 'Ficha Produto Químico';
COMMENT ON TABLE public.historicoocoracidente IS 'Histórico de Ocorrências de Acidentes';
COMMENT ON TABLE public.meioimpactado IS 'Área Impactada';
COMMENT ON TABLE public.municipio2007ibge1000k IS 'Relação das Cidades Cadastradas';
COMMENT ON TABLE public.passivoambiental IS 'Passivo Ambiental';
COMMENT ON TABLE public.produtoquimareacontaminada IS 'Produto Químico - Área Contaminada';
COMMENT ON TABLE public.rechidrrepresentativo IS 'Recursos Hídricos Representativos';
COMMENT ON TABLE public.refprodutoperigoso IS 'Registro de Ocorrência com Produto Perigoso';
COMMENT ON TABLE public.refresiduo IS 'Classes de resíduo';
COMMENT ON TABLE public.residuoareacontampasamb IS 'Resíduo - Área Contaminada Passivo Ambiental';
COMMENT ON TABLE public.sitiofragilvulneravel IS 'Relação de Sítios Frágeis e Vulneráveis';
COMMENT ON TABLE public.trechoeixoviaprincipal IS 'Trecho Eixo Via Principal';
COMMENT ON TABLE public.unidadefederativa IS 'Relação dos Estados Cadastrados';
COMMENT ON TABLE public.unidaderespacidente IS 'Unidades de Resposta a Acidentes';